# Generated by Django 4.1.7 on 2023-03-09 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertiesemployed',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='propertiesemployed',
            name='total',
        ),
        migrations.AlterField(
            model_name='contact',
            name='abn_or_acn_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='ABN/ACN Number (Numbers Only)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('', '-----------'), ('Branch', 'Branch'), ('Head Office', 'Head Office')], default='', max_length=100, null=True, verbose_name='Type*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='insurance_cover_amount',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter whole numbers.', regex='^[\\d\\,.]*$')], verbose_name='Insurance Cover Amount ($) (Numbers Only)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='License Number (Numbers & Letters Only)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Number (Numbers & Letters Only)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_fax',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'XXXXXXXXXX' or '(XX) XXXXXXXXXX'. Up to 12 digits allowed.", regex='^[(\\d) ]{10,15}$')], verbose_name='Office Fax*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'XXXXXXXXXX' or '(XX) XXXXXXXXXX'. Up to 12 digits allowed.", regex='^[(\\d) ]{10,15}$')], verbose_name='Office Phone*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='rate_per_hour',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rate/hour ($) (Numbers Only)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='trade_rating',
            field=models.CharField(blank=True, choices=[('1/5', '1/5'), ('2/5', '2/5'), ('3/5', '3/5'), ('4/5', '4/5'), ('5/5', '5/5')], default='1/5', max_length=50, null=True, verbose_name='Trade Rating'),
        ),
    ]
