# Generated by Django 4.1.7 on 2023-03-09 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0024_auto_20220127_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afcacomplaintlodged',
            name='comments',
            field=models.CharField(blank=True, max_length=2555, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='afcacomplaintlodged',
            name='mobile',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: 'XXXXXXXXXX' or '(XX) XXXXXXXXXX'. Up to 12 digits allowed.", regex='^[(\\d) ]{10,15}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='external',
            name='thoughts',
            field=models.CharField(blank=True, max_length=2555, null=True, verbose_name='Thoughts'),
        ),
        migrations.AlterField(
            model_name='externalmaterials',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='feasibilityreport',
            name='comments',
            field=models.CharField(blank=True, max_length=2555, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='listforsale',
            name='result',
            field=models.CharField(choices=[('Please Select', 'Please Select'), ('Listed', 'Listed'), ('Exchanged', 'Exchanged'), ('Sold', 'Sold')], default='Please Select', max_length=50, verbose_name='Sale Status'),
        ),
        migrations.AlterField(
            model_name='listforsale',
            name='sale_method',
            field=models.CharField(choices=[('Please Select', 'Please Select'), ('Auction', 'Auction'), ('Private Treaty', 'Private Treaty'), ('Tender', 'Tender')], default='Please Select', max_length=50, verbose_name='Sale Method'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='primecostitems',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchasecomparablesales',
            name='accommodation',
            field=models.CharField(choices=[('Inferior', 'Inferior'), ('Comparable', 'Comparable'), ('Superior', 'Superior'), ('Please Select', 'Please Select')], default='Please Select', max_length=20, verbose_name='Accommodation'),
        ),
        migrations.AlterField(
            model_name='purchasecomparablesales',
            name='bath',
            field=models.CharField(default=0, max_length=100, verbose_name='Bath'),
        ),
        migrations.AlterField(
            model_name='purchasecomparablesales',
            name='beds',
            field=models.CharField(default=0, max_length=100, verbose_name='Beds'),
        ),
        migrations.AlterField(
            model_name='purchasecomparablesales',
            name='construction',
            field=models.CharField(choices=[('Inferior', 'Inferior'), ('Comparable', 'Comparable'), ('Superior', 'Superior'), ('Please Select', 'Please Select')], default='Please Select', max_length=20, verbose_name='Construction'),
        ),
        migrations.AlterField(
            model_name='purchasecomparablesales',
            name='garage',
            field=models.CharField(default=0, max_length=100, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='purchasecomparablesales',
            name='improvements',
            field=models.CharField(choices=[('Inferior', 'Inferior'), ('Comparable', 'Comparable'), ('Superior', 'Superior'), ('Please Select', 'Please Select')], default='Please Select', max_length=20, verbose_name='Improvements'),
        ),
        migrations.AlterField(
            model_name='purchasecomparablesales',
            name='land',
            field=models.CharField(default=0, max_length=100, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='purchasecomparablesales',
            name='location',
            field=models.CharField(choices=[('Inferior', 'Inferior'), ('Comparable', 'Comparable'), ('Superior', 'Superior'), ('Please Select', 'Please Select')], default='Please Select', max_length=20, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='purchasecomparablesales',
            name='overall_comparability',
            field=models.CharField(choices=[('Inferior', 'Inferior'), ('Comparable', 'Comparable'), ('Superior', 'Superior'), ('Please Select', 'Please Select')], default='Please Select', max_length=20, verbose_name='Overall Comparability'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_thoughts',
            field=models.CharField(blank=True, max_length=2555, null=True, verbose_name='Thoughts'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='additional_cost_comments',
            field=models.CharField(blank=True, max_length=2555, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='salecomparablesales',
            name='bath',
            field=models.CharField(default=0, max_length=100, verbose_name='Bath'),
        ),
        migrations.AlterField(
            model_name='salecomparablesales',
            name='beds',
            field=models.CharField(default=0, max_length=100, verbose_name='Beds'),
        ),
        migrations.AlterField(
            model_name='salecomparablesales',
            name='garage',
            field=models.CharField(default=0, max_length=100, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='salecomparablesales',
            name='land',
            field=models.CharField(default=0, max_length=100, verbose_name='Land'),
        ),
    ]
